import "./globals.css";

// 2. PrimeReact Core & Theme (CRITICAL)
import "primereact/resources/themes/lara-light-indigo/theme.css"; 
import "primereact/resources/primereact.min.css";                                 
import "primeicons/primeicons.css";

// 3. AG Grid Styles (CRITICAL)
import 'ag-grid-community/styles/ag-grid.css';
import 'ag-grid-community/styles/ag-theme-alpine.css'; // or ag-theme-quartz

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* 1. 'h-screen' e 'overflow-hidden': Mantemos isto aqui para garantir
            que a página inteira não rola, mantendo a Navbar fixa.
      */}
      <body className="h-screen flex flex-col overflow-hidden">
        
        <Navbar />

        {/* 2. ALTERAÇÃO AQUI:
           Mudamos de 'overflow-hidden' para 'overflow-auto'.
           Isto diz: "Se o conteúdo (children) for maior que o espaço disponível,
           cria uma barra de scroll APENAS nesta área, por baixo da Navbar."
        */}
        <div className="flex-1 w-full overflow-auto bg-gray-50">
            {children}
        </div>

      </body>
    </html>
  );
}